---
title: ""
output: html_document
params:
  program:
    label: "Program Type:"
    value: All during period
    input: select
    choices: [All during period,
              Crop insurance,
              ARC,
              PLC,
              SCO,
              CCP,
              ACRE,
              Market loss assistance,
              Fixed direct payment (contract payment),
              Marketing Loan program,
              Milk Income Loss Contract (MILC),
              Margin Protection Program,
              Pre-1996 US policy,
              Other]
  supply:
    label: "Supply Type:"
    value: Area of a Crop or Crops
    input: select
    choices: [Area of a Crop or Crops,
              Yield,
              Production of a Crop or Crops]
  savePCOPUP:
    label: "Save PCOPUP Table?"
    value: TRUE
  savePI2MI:
    label: "Save PI2MI Table?"
    value: TRUE
  saveElasMarket:
    label: "Save Market Elasticity Table?"
    value: TRUE
  saveElasPayment:
    label: "Save Market Payment Table?"
    value: TRUE
---
<style>
.main-container {
max-width: 940px;
margin-left: 0;
margin-right: auto;
color: black;
}

caption {
color: black;
font-weight: bold;
}

</style>

```{r, echo = FALSE}

selectedProgramText = params$program
selectedSupplyText = params$supply
savePCOPUPStatus = params$savePCOPUP
savePI2MIStatus = params$savePI2MI
saveElasMarketStatus = params$saveElasMarket
saveElasPaymentStatus = params$saveElasPayment

```


```{r, include = FALSE}

source("DecouplingTables.R")

```


```{r, echo = FALSE, results = 'asis'}

tablePCOPUP
cat("\n\n\\pagebreak\n")
tablePI2MI

```



